/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function FilterOptions() {
  return (
    <div className="flex flex-1 gap-6 my-auto max-md:max-w-full">
      <div className="flex gap-3 my-auto text-xl whitespace-nowrap">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/842436d794fc0cfeb3e34f2c14af76e0f72a024d4010bb3b1a75369fdbc06f48?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0" className="object-contain shrink-0 my-auto aspect-square w-[25px]" alt="" />
        <div>Filter</div>
      </div>
      <div className="flex flex-auto gap-6 items-center text-base">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/2fe97d5aee6620cb7df08144b1117f322cabc7502580f5d40d34041285247887?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0" className="object-contain shrink-0 self-stretch my-auto w-7 aspect-square" alt="" />
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/a155f592a627e635322117912e0d640704bcf03fc3e00020b82570d141909f48?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0" className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square" alt="" />
        <div className="shrink-0 self-stretch w-0.5 border-2 border-solid border-neutral-400 h-[37px]" />
        <div className="self-stretch my-auto basis-auto">
          Showing 1–16 of 32 results
        </div>
      </div>
    </div>
  );
}

export default FilterOptions;