/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import FilterOptions from './FilterOptions';
import ResultsDisplay from './ResultsDisplay';
import SortOptions from './SortOptions';

function FilterComponent() {
  return (
    <section className="flex flex-col text-black">
      <div className="flex flex-wrap gap-10 px-20 py-6 w-full bg-orange-50 max-md:px-5 max-md:max-w-full">
        <FilterOptions />
        <ResultsDisplay />
        <SortOptions />
      </div>
    </section>
  );
}

export default FilterComponent;