/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function ResultsDisplay() {
  return (
    <div className="flex flex-1 gap-4 text-xl max-md:max-w-full">
      <label htmlFor="showResults" className="my-auto">Show</label>
      <select id="showResults" className="px-5 whitespace-nowrap bg-white h-[55px] text-neutral-400 w-[55px]" aria-label="Number of results to show">
        <option>16</option>
      </select>
    </div>
  );
}

export default ResultsDisplay;