/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function TableRow({ id, customer, date, total, method, status }) {
  return (
    <div className="flex flex-wrap items-center pr-6 pl-4 w-full text-base leading-none border-b border-violet-100 text-zinc-800 max-md:pr-5 max-md:max-w-full">
      <div className="flex flex-1 shrink gap-2.5 items-center self-stretch px-5 py-2 my-auto whitespace-nowrap border-0 border-solid basis-0 border-zinc-300 text-zinc-800">
        <div className="self-stretch my-auto">{id}</div>
      </div>
      <div className="flex-1 shrink gap-2 self-stretch px-5 py-5 my-auto border-0 border-solid border-zinc-300">{customer}</div>
      <div className="flex-1 shrink gap-2 self-stretch px-5 py-5 my-auto border-0 border-solid border-zinc-300">{date}</div>
      <div className="flex-1 shrink gap-2 self-stretch px-5 py-5 my-auto whitespace-nowrap border-0 border-solid border-zinc-300">{total}</div>
      <div className="flex-1 shrink gap-2.5 self-stretch px-5 py-3.5 my-auto whitespace-nowrap border-0 border-solid border-zinc-300">{method}</div>
      <div className="flex-1 shrink gap-2.5 self-stretch px-5 py-3.5 my-auto font-semibold leading-none text-yellow-400 whitespace-nowrap border-0 border-solid border-zinc-300">{status}</div>
      <div className="flex-1 shrink gap-2.5 self-stretch px-5 py-3.5 my-auto text-blue-600 border-0 border-solid border-zinc-300">
        <button className="focus:outline-none focus:ring-2 focus:ring-blue-300" onClick={() => console.log(`View details for ${id}`)}>
          View Details
        </button>
      </div>
    </div>
  );
}

export default TableRow;