/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function TableHeader() {
  return (
    <div className="flex flex-wrap items-start pr-6 pl-4 w-full text-sm font-medium uppercase whitespace-nowrap border-b border-violet-100 text-neutral-400 max-md:pr-5 max-md:max-w-full">
      <div className="flex-1 shrink gap-1 self-stretch px-5 py-4">ID</div>
      <div className="flex-1 shrink gap-1 self-stretch px-5 py-4">Customer</div>
      <div className="flex-1 shrink gap-1 self-stretch px-5 py-4 w-[61px]">Date</div>
      <div className="flex-1 shrink gap-1 self-stretch px-5 py-4">Total</div>
      <div className="flex-1 shrink gap-1 self-stretch px-5 py-4">Method</div>
      <div className="flex-1 shrink gap-1 self-stretch px-5 py-4">Status</div>
      <div className="flex-1 shrink gap-1 self-stretch px-5 py-4">Action</div>
    </div>
  );
}

export default TableHeader;