/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import TableHeader from './TableHeader';
import TableRow from './TableRow';
import TablePagination from './TablePagination';

const transactionData = [
  { id: '#5089', customer: 'Joseph Wheeler', date: '6 April, 2023', total: '$2,564', method: 'CC', status: 'Pending' },
  { id: '#5089', customer: 'Joseph Wheeler', date: '6 April, 2023', total: '$2,564', method: 'CC', status: 'Pending' },
  { id: '#5089', customer: 'Joseph Wheeler', date: '6 April, 2023', total: '$2,564', method: 'CC', status: 'Pending' },
  { id: '#5089', customer: 'Joseph Wheeler', date: '6 April, 2023', total: '$2,564', method: 'CC', status: 'Pending' },
  { id: '#5089', customer: 'Joseph Wheeler', date: '6 April, 2023', total: '$2,564', method: 'CC', status: 'Pending' },
  { id: '#5089', customer: 'Joseph Wheeler', date: '6 April, 2023', total: '$2,564', method: 'CC', status: 'Pending' },
  { id: '#5089', customer: 'Joseph Wheeler', date: '6 April, 2023', total: '$2,564', method: 'CC', status: 'Pending' },
  { id: '#5089', customer: 'Joseph Wheeler', date: '6 April, 2023', total: '$2,564', method: 'CC', status: 'Pending' },
  { id: '#5089', customer: 'Joseph Wheeler', date: '6 April, 2023', total: '$2,564', method: 'CC', status: 'Pending' },
  { id: '#5089', customer: 'Joseph Wheeler', date: '6 April, 2023', total: '$2,564', method: 'CC', status: 'Pending' },
];

function TransactionTable() {
  return (
    <section className="flex flex-col pt-2 mt-4 bg-white rounded-2xl max-md:max-w-full">
      <div className="flex flex-col w-full max-md:max-w-full">
        <TableHeader />
        {transactionData.map((transaction, index) => (
          <TableRow key={index} {...transaction} />
        ))}
        <TablePagination />
      </div>
    </section>
  );
}

export default TransactionTable;