/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function TransactionHeader() {
  return (
    <header className="flex flex-col w-full max-md:mr-1 max-md:max-w-full">
      <div className="flex overflow-hidden flex-wrap gap-2.5 justify-center py-3 w-full rounded-md shadow-sm min-h-[62px] max-md:max-w-full">
        <h1 className="flex-1 shrink gap-2.5 self-stretch h-full text-2xl font-bold leading-none whitespace-nowrap min-w-[240px] text-zinc-800 max-md:max-w-full">
          Transaction
        </h1>
        <div className="flex gap-6 items-center self-start">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/595202b9fc4acab98d01d55e67fcbe04c420b59a418bb14c659c0cf3f3197fb6?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0" alt="" className="object-contain shrink-0 self-stretch my-auto w-7 aspect-[0.76]" />
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/702b22a5d97cb86420758f8c8aba74994c3c94b03f249054e32f4d6982d5731c?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0" alt="" className="object-contain shrink-0 self-stretch my-auto aspect-square w-[38px]" />
        </div>
      </div>
    </header>
  );
}

export default TransactionHeader;