/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import TransactionHeader from './TransactionHeader';
import TransactionFilters from './TransactionFilters';
import TransactionTable from '../TransactionTable/TransactionTable';

function TransactionPage() {
  return (
    <main className="flex flex-col">
      <TransactionHeader />
      <TransactionFilters />
      <TransactionTable />
    </main>
  );
}

export default TransactionPage;