/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function TransactionFilters() {
  return (
    <div className="flex flex-wrap gap-5 justify-between mt-6 w-full text-base max-md:mr-0.5 max-md:max-w-full">
      <div className="flex gap-4">
        <div className="flex items-center leading-snug whitespace-nowrap bg-white rounded shadow-sm min-h-[40px] text-neutral-400">
          <div className="flex overflow-hidden flex-1 shrink gap-1 items-center self-stretch px-4 py-2 my-auto w-full rounded basis-0">
            <label htmlFor="searchInput" className="sr-only">Search</label>
            <input
              id="searchInput"
              type="text"
              placeholder="Search..."
              className="flex-1 shrink self-stretch my-auto basis-0 bg-transparent border-none focus:outline-none"
            />
            <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/7294a7495a148aca21eb4d1e7fe45468db9fbef9446ddfbcfe9d3f1a4f4fe363?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0" alt="" className="object-contain shrink-0 self-stretch my-auto aspect-square w-[18px]" />
          </div>
        </div>
        <div className="flex overflow-hidden items-start font-medium tracking-wide bg-white rounded-md shadow-[0px_4px_16px_rgba(0,0,0,0.04)] text-neutral-400">
          <button className="flex gap-1.5 justify-center items-center px-4 py-3 min-h-[40px]">
            <span className="self-stretch my-auto">Status : All</span>
            <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/1ad593abdf638125bd46073fafeac8d45f3df0000ae5af424cdd37573a645233?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0" alt="" className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square" />
          </button>
        </div>
      </div>
      <div className="flex overflow-hidden items-start font-medium tracking-wide bg-white rounded-md shadow-[0px_4px_16px_rgba(0,0,0,0.04)] text-neutral-400">
        <button className="flex gap-1.5 justify-center items-center px-4 py-3 min-h-[40px]">
          <span className="self-stretch my-auto">Filter by date range</span>
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/1ad593abdf638125bd46073fafeac8d45f3df0000ae5af424cdd37573a645233?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0" alt="" className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square" />
        </button>
      </div>
    </div>
  );
}

export default TransactionFilters;