/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ImageGrid from "./ImageGrid";
import Header from "./Header";

const images = [
  { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/79e1fc94d46a4e77fb108532d218695782769f3df4d1218c3d34bae6fa1fbd83?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0", className: "mt-14 max-w-full aspect-[1.45] w-[451px] max-md:mt-10" },
  { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/889d0504ac61daca9109b091e81306889b9db5c2a32024042224541ec88c4a9e?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0", className: "z-10 self-end mt-0 max-w-full aspect-[0.6] w-[262px] max-md:mt-0" },
  { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/74a0f0e7a0cb357eb584f13b2709e426228c3d97f4201dc3b416124a3d7514fd?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0", className: "z-10 self-end mt-0 mr-72 max-w-full aspect-[0.83] w-[290px] max-md:mt-0 max-md:mr-2.5" },
  { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/445f86297c7ccdeb7fe19469482d56bafd74ff85bbb57fab4d42b7e951a3af2b?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0", className: "self-center mt-0 max-w-full aspect-[0.75] w-[295px] max-md:mt-0" },
];

function FuniroFurniture() {
  return (
    <main className="flex flex-col pb-4">
      <Header />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/bb52bac2a98c7a31b89bc9e8c623b81b0389d49e8e13897cc63b2b1514368694?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0"
        alt=""
        className="object-contain mt-0 aspect-[0.2] w-[78px]"
      />
      <section className="flex z-10 flex-col pt-14 pl-20 mt-0 w-full max-md:pl-5 max-md:mt-0 max-md:max-w-full">
        <ImageGrid images={images} />
      </section>
      <ImageGrid
        images={[
          { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/9b0799b9bd039b298ebdd97983b29ab7c2f1e0106ce1777df246acaab7ee0757?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0", className: "grow shrink-0 max-w-full aspect-[0.57] w-[185px] max-md:mt-4" },
          { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/0f5c0689e293601be4d2a8c70c3c535415737863c66e451d47e028744db76c1b?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0", className: "w-full aspect-[1.42] max-md:mt-4" },
        ]}
        containerClassName="z-10 mt-0 max-w-full w-[545px]"
        gridClassName="flex gap-5 max-md:flex-col"
        columnClassNames={["w-[35%] max-md:ml-0 max-md:w-full", "ml-5 w-[65%] max-md:ml-0 max-md:w-full"]}
      />
      <ImageGrid
        images={[
          { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/dde29ec771b49702e2652bb8327c9a3acaef7cca1398125dcff5960e74fdab79?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0", className: "grow shrink-0 max-w-full aspect-[0.74] w-[178px] max-md:mt-4" },
          { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/f527035f35aecf487e1168ef76637d5a7ad20fb4c257d5548d8c4fce31b30cb5?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0", className: "w-full aspect-[1.32] max-md:mt-4" },
        ]}
        containerClassName="self-end mt-0 mr-28 max-w-full w-[452px] max-md:mt-0 max-md:mr-2.5"
        gridClassName="flex gap-5 max-md:flex-col"
        columnClassNames={["w-[41%] max-md:ml-0 max-md:w-full", "ml-5 w-[59%] max-md:ml-0 max-md:w-full"]}
      />
    </main>
  );
}

export default FuniroFurniture;