/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function CustomerTableRow({ name, email, phone, created }) {
  return (
    <div className="flex flex-wrap items-center pr-6 pl-4 w-full border-b border-violet-100 max-md:pr-5 max-md:max-w-full">
      <div className="flex flex-1 shrink gap-2.5 items-center self-stretch px-5 py-4 my-auto text-base leading-none border-0 border-solid basis-0 border-zinc-300 min-w-[240px]">
        <div className="flex gap-2 items-center self-stretch my-auto w-[117px]">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/a63ea1a1bcd88b5c80c5683236f42957a4dd62a47ef11d232d3ef48697f444cf?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0" className="object-contain shrink-0 self-stretch my-auto w-8 aspect-square rounded-[100px]" alt={`${name}'s profile`} />
          <div className="flex flex-col justify-center self-stretch my-auto">
            <div className="font-semibold text-zinc-800">{name}</div>
            <div className="text-neutral-400">{email}</div>
          </div>
        </div>
      </div>
      <div className="flex-1 shrink gap-2.5 self-stretch px-5 py-3.5 my-auto text-base leading-none border-0 border-solid border-zinc-300 min-w-[240px] text-zinc-800">
        {phone}
      </div>
      <div className="flex-1 shrink gap-2.5 self-stretch px-5 py-3.5 my-auto text-base leading-none border-0 border-solid border-zinc-300 min-w-[240px] text-zinc-800">
        {created}
      </div>
      <div className="flex flex-1 shrink gap-2.5 items-center self-stretch px-5 py-3.5 my-auto basis-0 min-w-[240px]">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/98115e1b3a830c04b99df200f82919c0247860c9db65a6e539f2a6596ed3c0fc?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0" className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square" alt="Action 1" />
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/5aa64876901d76ba8aa7fb465c250cffc3ef36cf3e36ad1277374b36d50ccab3?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0" className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square" alt="Action 2" />
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/9b56829d08775646f475805ac4f57dc155082ee04afb538cb78683992ecfc29a?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0" className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square" alt="Action 3" />
      </div>
    </div>
  );
}

export default CustomerTableRow;