/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function CustomerTableHeader() {
  return (
    <div className="flex flex-wrap items-start pr-6 pl-4 w-full text-sm font-medium uppercase border-b border-violet-100 text-neutral-400 max-md:pr-5 max-md:max-w-full">
      <div className="flex-1 shrink gap-1 self-stretch px-5 py-4 whitespace-nowrap min-w-[240px]">
        Name
      </div>
      <div className="flex-1 shrink gap-1 self-stretch px-5 py-4 min-w-[240px]">
        Phone Number
      </div>
      <div className="flex-1 shrink gap-1 self-stretch px-5 py-4 whitespace-nowrap min-w-[240px]">
        Created
      </div>
      <div className="flex-1 shrink gap-1 self-stretch px-5 py-4 whitespace-nowrap min-w-[240px]">
        Action
      </div>
    </div>
  );
}

export default CustomerTableHeader;