/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function SearchBar() {
  return (
    <form className="flex items-center self-start mt-6 text-base leading-snug whitespace-nowrap bg-white rounded shadow-sm min-h-[40px] text-neutral-400">
      <div className="flex overflow-hidden flex-1 shrink gap-1 items-center self-stretch px-4 py-2 my-auto w-full rounded basis-0">
        <label htmlFor="search" className="sr-only">Search</label>
        <input
          type="text"
          id="search"
          placeholder="Search..."
          className="flex-1 shrink self-stretch my-auto basis-0 bg-transparent border-none focus:outline-none"
        />
        <button type="submit" aria-label="Search">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/e3a1f6cf2db7335d20347fd0727768560ef08c79bd7c830622bc7f32e44b48f2?placeholderIfAbsent=true&apiKey=5f7c255a63be4d4b97b4f114fa9e17d0" className="object-contain shrink-0 self-stretch my-auto aspect-square w-[18px]" alt="" />
        </button>
      </div>
    </form>
  );
}

export default SearchBar;